package utility.IO;

public enum CommandsToClient {
  LOBBY,
  PRINT,
  INITIALPING,
  PING,
  CREATELOBBY,
  PRINTUSERLIST,
  PRINTLOUNGINGLIST,
  PRINTOPENLOBBIES,
  PRINTFINISHEDLOBBIES,
  PRINTONGOINGLOBBIES,
  CHANGELOBBY,
  PRINTLOBBIES
}
